#!/usr/bin/env bash
# displays Best School and then Hi on a new line

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
        then
            echo $"hi"
    fi
    echo $"Best School"
    i=$((i+1))
done
