#!/usr/bin/env bash
# displays Best School and then Hi on a new line

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 8 ]
        then
            echo $"Hi"
    else
        echo $"Best School"
    
    fi
    i=$((i+1))
done
