#!/usr/bin/env bash
# clock

i=0
j=1

while [ $i -lt 13 ]
do
    j=1
    echo $"Hour: $i"
    while [ $j -lt 60 ]
        do
            echo $j
            j=$((j+1))
        done
    i=$((i+1))
    case $i in
        12)
            echo $"Hour: 12"
            exit 0
            ;;
    esac
done
