#!/usr/bin/env bash
# to file or not to file

FILE=./school

if test -f $FILE || test -d $FILE; then
    echo $"school file exists"
    if [ -s $FILE ];then
        echo $"school file is not empty"

    else
        echo $"school file is empty"
    fi
    
    if  ! test -d $FILE ;then
        echo $"school is a regular file" 
    fi

else
    echo $"school file does not exist"

fi
